T: 4
algo: dac
bc_weight: 0.8
d4rl: true
discount2: 1.0
env_name: hopper-medium-v2
format:
- stdout
- wandb
- csv
id: hopp-t4-infer4-ddpm-bc0.8-sept14-nb-hopbc
n_inf_steps: 4
name: hopp-t4-infer4-ddpm-bc0.8-sept14-nb-hopbc
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
sampler_type: ddpm
tune_bc_weight: false
vec_env_eval: true
