T: 16
algo: dql
bc_weight: 0.2
d4rl: true
discount2: 0.999
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: dql-halfch-q-ema-offline-t16
name: dql-halfch-q-ema-offline-t16
need_animation: true
need_entropy_test: true
num_steps_per_epoch: 1
online: false
predict_epsilon: false
update_ema_every: 1
