T: 1
ablation: true
algo: dac
bc_weight: 0.0
d4rl: true
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: dac-t1-sept3-dql-dac-online
name: dac-t1-sept3-dql-dac-online
num_epochs: 10000
num_steps_per_epoch: 500
predict_epsilon: false
test_critic: true
