T: 1
algo: vae-ac
bc_decay: 0.995
bc_lower_bound: 0.01
bc_upper_bound: 100.0
bc_weight: 2.5
coef: 1.0
discount2: 0.999
env_name: walker2d-medium-v2
id: walker-vae-2.5
name: walker-vae-2.5
seed: 0
tune_bc_weight: false
value_threshold: 0.00028
