T: 8
ablation: true
algo: dql
d4rl: true
discount2: 1.0
env_name: hopper-medium-v2
format:
- stdout
- wandb
- csv
id: hopp-t8-infer8-origin-dql-sept19-nb-hopbc
n_inf_steps: 8
name: hopp-t8-infer8-origin-dql-sept19-nb-hopbc
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
sampler_type: origin
test_critic: true
tune_bc_weight: false
vec_env_eval: true
