T: 8
algo: dql
d4rl: true
discount2: 1.0
env_name: hopper-medium-v2
format:
- stdout
- wandb
- csv
id: hopp-t8-dql-sept19-nb-hopbc
name: hopp-t8-dql-sept19-nb-hopbc
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
tune_bc_weight: false
vec_env_eval: true
