T: 8
action_len: 3
algo: tmac
bc_weight: 1.0
critic_ema: 1
d4rl: true
discount2: 1.0
env_name: hopper-medium-v2
eval_steps: 2
format:
- stdout
- wandb
- csv
id: hopp-t8-sl2-infer2-ddpm-roll1-sept23-nb-statelen
len_rollout: 1
n_inf_steps: 2
name: hopp-t8-sl2-infer2-ddpm-roll1-sept23-nb-statelen
num_steps_per_epoch: 50000
online: false
policy_delay: 1
predict_epsilon: false
resample: true
sampler_type: ddpm
state_len: 2
trajectory: true
tune_bc_weight: false
update_ema_every: 5
vec_env_eval: false
