T: 4
algo: dac
d4rl: true
env_name: halfcheetah-medium-v2
format:
- stdout
- csv
id: entropy-dac-halfch-online-t4
name: entropy-dac-halfch-online-t4
need_animation: true
predict_epsilon: false
update_ema_every: 1
need_entropy_test: True
num_steps_per_epoch: 1
online: false