T: 2
algo: dql
bc_weight: 1.0
d4rl: false
env_name: Demo-v0
format:
- stdout
- wandb
id: dql-demo-offline-t2
name: dql-demo-offline-t2
need_animation: true
num_steps_per_epoch: 1
predict_epsilon: false
update_ema_every: 1
vis_q: true
