T: 8
algo: dac
d4rl: true
discount2: 0.999
env_name: walker2d-medium-v2
format:
- stdout
- wandb
- csv
id: dac-walker-q-online-t8
name: dac-walker-q-online-t8
need_animation: true
need_entropy_test: true
predict_epsilon: false
update_ema_every: 1
