T: 1
algo: dac
d4rl: true
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
id: dac-halfch-mujoco-online-t1
name: dac-halfch-mujoco-online-t1
need_animation: true
predict_epsilon: false
update_ema_every: 1
