T: 4
algo: dac
d4rl: true
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
id: dac-halfch-mujoco-online-t4
name: dac-halfch-mujoco-online-t4
need_animation: true
predict_epsilon: false
update_ema_every: 1
