T: 4
algo: bc
d4rl: true
env_name: halfcheetah-medium-v2
format:
  - stdout
  - csv
  - wandb
id: bc-halfch-offline-t4
name: bc-halfch-offline-t4
need_animation: true
predict_epsilon: false
update_ema_every: 1
need_entropy_test: True
num_steps_per_epoch: 1
online: false
