T: 8
algo: dac
bc_weight: 1.0
d4rl: true
discount2: 1.0
env_name: hopper-medium-v2
format:
- stdout
- wandb
- csv
id: hopp-t8-infer4-ddpm-bc1.0-sept15-nb-hopbc
n_inf_steps: 4
name: hopp-t8-infer4-ddpm-bc1.0-sept15-nb-hopbc
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
sampler_type: ddpm
tune_bc_weight: false
vec_env_eval: true
