T: 4
algo: dql
beta_schedule: cosine
d4rl: false
env_name: Demo-v0
format:
- stdout
- wandb
id: dql-demo-offline-t4
name: dql-demo-offline-t4
need_animation: true
predict_epsilon: false
update_ema_every: 1
vis_q: true
