T: 8
algo: dac
d4rl: true
discount2: 1.0
env_name: hopper-medium-v2
format:
- stdout
- wandb
- csv
id: hopp-t8-infer8-ddpm-sept19-nb-dac
n_inf_steps: 8
name: hopp-t8-infer8-ddpm-sept19-nb-dac
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
sampler_type: ddpm
tune_bc_weight: false
vec_env_eval: true
