T: 1
algo: dac
bc_decay: 0.995
bc_lower_bound: 0.01
bc_upper_bound: 100.0
bc_weight: 7.5
coef: 1.0
discount2: 0.999
env_name: halfcheetah-medium-v2
id: halfch-scale-1e-06
name: halfch-scale-1e-06
scale: 1.0e-06
seed: 0
tune_bc_weight: false
value_threshold: 0.00028
