T: 4
algo: dql
bc_weight: 1.0
d4rl: true
discount2: 0.999
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: dql-halfch-q2-offline-t4
name: dql-halfch-q2-offline-t4
need_animation: true
need_entropy_test: true
num_steps_per_epoch: 1
online: false
predict_epsilon: false
update_ema_every: 1
