T: 1
algo: dac
bc_weight: 0.01
d4rl: true
discount2: 0.999
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: halfch-t1-sept10-dac-pre-critic
name: halfch-t1-sept10-dac-pre-critic
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
seed: 0
test_critic: true
tune_bc_weight: false
