T: 1
ablation: true
algo: dac
bc_weight: 0.2
d4rl: true
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: dac-t1-sept4-dac-bcw
name: dac-t1-sept4-dac-bcw
num_epochs: 10000
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
test_critic: true
