T: 1
algo: dac
bc_decay: 0.995
bc_lower_bound: 0.01
bc_upper_bound: 100.0
bc_weight: 0.01
coef: 1.0
consistency: true
discount2: 0.999
env_name: halfcheetah-medium-v2
id: halfch-dac-con-bcw-low-t1
name: halfch-dac-con-bcw-low-t1
predict_epsilon: false
seed: 0
tune_bc_weight: false
value_threshold: 0.00028
