T: 8
algo: ql
env_name: antmaze-umaze-v0
eta: 0.5
format:
- stdout
- wandb
- csv
gn: 2.0
id: antmaze-umaze-v0-dql-nov16
lr: 0.0003
max_q_backup: false
name: antmaze-umaze-v0-dql-nov16
predict_epsilon: false
reward_tune: cql_antmaze
seed: 0
