T: 8
algo: ql
env_name: antmaze-large-diverse-v0
eta: 3.5
eval_freq: 50
format:
- stdout
- wandb
- csv
gn: 7.0
id: antmaze-large-diverse-v0-dql-nov16
lr: 0.0003
max_q_backup: true
name: antmaze-large-diverse-v0-dql-nov16
num_epochs: 1000
num_steps_per_epoch: 5000
predict_epsilon: false
reward_tune: cql_antmaze
seed: 0
