T:
- 2
- 3
- 4
algo: ql
env_name: antmaze-umaze-diverse-v0
eta: 2.0
eval_freq: 50
format:
- stdout
- wandb
- csv
gn: 3.0
id: antmaze-umaze-diverse-v0-dql-nov16
lr: 0.0003
max_q_backup: true
name: antmaze-umaze-diverse-v0-dql-nov16
num_epochs: 1000
num_steps_per_epoch: 5000
predict_epsilon: false
reward_tune: cql_antmaze
seed: 0
