algo: "dac" 
T: 1 
update_ema_every: 1 
name: "dac-halfch-online-t1" 
id: "dac-halfch-online-t1" 
predict_epsilon: False 
# format: ['stdout', "wandb"]
# env_name: "Demo-v0"
env_name: "halfcheetah-medium-v2"
need_animation: True
d4rl: True