T: 4
algo: dac
bc_weight: 1.0
d4rl: true
discount2: 1.0
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: dac-halfch-t4-bcw1.0-tvec-offline
name: dac-halfch-t4-bcw1.0-tvec-offline
need_animation: true
need_entropy_test: true
num_steps_per_epoch: 1
online: false
predict_epsilon: false
update_ema_every: 1
