T: 4
algo: dac
bc_weight: 0.2
d4rl: true
discount2: 1.0
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: dac-halfch-t-vec-offline-t4
name: dac-halfch-t-vec-offline-t4
need_animation: true
need_entropy_test: true
num_steps_per_epoch: 1
online: false
predict_epsilon: false
update_ema_every: 1
