T: 4
algo: dql
bc_weight: 0.2
d4rl: true
discount2: 1.0
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: dql-halfch-t4-bcw0.2-tvec-offline
name: dql-halfch-t4-bcw0.2-tvec-offline
need_animation: true
need_entropy_test: true
num_steps_per_epoch: 1
online: false
predict_epsilon: false
update_ema_every: 1
