MSBE_coef: 1.0
T: 1
algo: dac
bc_weight: 0.01
critic_ema: 1
d4rl: true
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: dac-t1-bc0.01-sept10-dac-bcw-shape
name: dac-t1-bc0.01-sept10-dac-bcw-shape
num_epochs: 10000
num_steps_per_epoch: 5000
online: false
policy_delay: 1
predict_epsilon: false
