T: 8
algo: mac
bc_weight: 0.1
d4rl: true
discount2: 1.0
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: half-t8-infer2-ddpm-roll4-sept20-nb-halfmac
len_rollout: 4
n_inf_steps: 2
name: half-t8-infer2-ddpm-roll4-sept20-nb-halfmac
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
sampler_type: ddpm
tune_bc_weight: false
vec_env_eval: true
