T: 4
algo: bc
bc_weight: 1.0
d4rl: true
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: t4-sept3-diffusion-bc-unit-test
name: t4-sept3-diffusion-bc-unit-test
num_epochs: 10000
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
