T: 8
ablation: true
algo: dac
bc_weight: 0.2
d4rl: true
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: dac-t8-bc0.2-sept6-dac2
name: dac-t8-bc0.2-sept6-dac2
num_epochs: 10000
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
test_critic: true
