T: 4
ablation: true
algo: dac
bc_weight: 0.0
d4rl: true
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: dac-t4-sept4-dql-dac-online
name: dac-t4-sept4-dql-dac-online
num_epochs: 10000
num_steps_per_epoch: 500
predict_epsilon: false
test_critic: true
