T: 8
action_len: 3
algo: mac
batch_size: 1024
bc_weight: 1.0
critic_ema: 1
d4rl: true
discount2: 1.0
env_name: antmaze-medium-play-v0
eta: 2.0
eval_freq: 50
eval_steps: 2
format:
- stdout
- wandb
- csv
gn: 2.0
grad_norm: 2.0
id: antmaze-medium-play-v0-roll1
len_rollout: 1
lr: 0.001
max_q_backup: true
n_inf_steps: 2
name: antmaze-medium-play-v0-roll1
num_epochs: 1000
num_steps_per_epoch: 5000
online: false
policy_delay: 2
predict_epsilon: false
resample: true
reward_tune: cql_antmaze
sampler_type: ddim
state_len: 4
top_k: 1
trajectory: false
tune_bc_weight: false
update_ema_every: 5
vec_env_eval: true
