T: 8
action_len: 3
algo: mac
bc_weight: 1.0
critic_ema: 1
d4rl: true
discount2: 1.0
env_name: halfcheetah-medium-replay-v2
eta: 1.0
eval_freq: 50
eval_steps: 2
format:
- stdout
- wandb
- csv
gn: 2.0
grad_norm: 2.0
id: f{env_name}-roll{rollout}
len_rollout: 1
lr: 0.0003
max_q_backup: false
n_inf_steps: 2
name: f{env_name}-roll{rollout}
num_epochs: 4000
num_steps_per_epoch: 5000
online: false
policy_delay: 2
predict_epsilon: false
resample: true
reward_tune: 'no'
sampler_type: ddim
state_len: 4
top_k: 0
trajectory: false
tune_bc_weight: false
update_ema_every: 5
vec_env_eval: true
