T: 8
action_len: 3
algo: mac
batch_size: 1024
bc_weight: 1.0
critic_ema: 1
d4rl: true
discount2: 1.0
env_name: hopper-medium-v2
eta: 1.0
eval_freq: 50
eval_steps: 2
format:
- stdout
- wandb
- csv
gn: 9.0
grad_norm: 9.0
id: hopper-medium-v2-roll1
len_rollout: 1
lr: 0.0003
max_q_backup: false
n_inf_steps: 2
name: hopper-medium-v2-roll1
num_epochs: 4000
num_steps_per_epoch: 5000
online: false
policy_delay: 2
predict_epsilon: false
resample: true
reward_tune: 'no'
sampler_type: ddim
state_len: 4
top_k: 2
trajectory: false
tune_bc_weight: false
update_ema_every: 5
vec_env_eval: true
