T: 8
action_len: 3
algo: mac
bc_weight: 1.0
critic_ema: 1
d4rl: true
discount2: 1.0
env_name: walker2d-medium-replay-v2
eta: 1.0
eval_freq: 50
eval_steps: 2
format:
- stdout
- wandb
- csv
gn: 4.0
grad_norm: 4.0
id: walker2d-medium-replay-v2-lr0.0003-eta1.0-maxq0-no-eval50-ep4000-gn4.0-top1-sept26-nb
len_rollout: 1
lr: 0.0003
max_q_backup: false
n_inf_steps: 2
name: walker2d-medium-replay-v2-lr0.0003-eta1.0-maxq0-no-eval50-ep4000-gn4.0-top1-sept26-nb
num_epochs: 4000
num_steps_per_epoch: 5000
online: false
policy_delay: 2
predict_epsilon: false
resample: true
reward_tune: 'no'
sampler_type: ddim
state_len: 4
top_k: 1
trajectory: false
tune_bc_weight: false
update_ema_every: 5
vec_env_eval: true
