T: 1
algo: dac
bc_decay: 0.995
bc_lower_bound: 0.01
bc_upper_bound: 100.0
bc_weight: 2.5
coef: 1.0
discount2: 0.999
env_name: halfcheetah-medium-v2
id: halfch-bcc-high-2.5
iql_style: discount
name: halfch-bcc-high-2.5
seed: 0
std_threshold: 0.0001
tune_bc_weight: true
value_threshold: 0.00028
