T: 1
algo: dac
bc_decay: 0.995
bc_lower_bound: 0.01
bc_upper_bound: 100.0
bc_weight: 20.0
coef: 1.0
discount2: 0.999
env_name: walker2d-medium-v2
id: walker-bcc-high-20.0
iql_style: discount
name: walker-bcc-high-20.0
seed: 0
std_threshold: 0.0001
tune_bc_weight: true
value_threshold: 0.00028
