T: 1
algo: pac
bc_weight: 0.01
d4rl: true
discount2: 0.999
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: pd1-t1-sept10-pac-pre-diff
name: pd1-t1-sept10-pac-pre-diff
num_steps_per_epoch: 5000
online: false
pre_dataset: true
predict_epsilon: false
seed: 0
tune_bc_weight: false
