T: 8
algo: dac
bc_weight: 1.0
d4rl: true
discount2: 0.999
env_name: walker2d-medium-v2
format:
- stdout
- wandb
- csv
id: dac-walker-discount2-offline-t8
name: dac-walker-discount2-offline-t8
need_animation: true
need_entropy_test: true
num_steps_per_epoch: 1
predict_epsilon: false
update_ema_every: 1
