T: 4
algo: dql
bc_weight: 1.0
d4rl: true
env_name: hopper-medium-v2
format:
- stdout
- wandb
id: dql-hopper-d4rl-offline-t4
name: dql-hopper-d4rl-offline-t4
need_animation: true
num_steps_per_epoch: 1
online: false
predict_epsilon: false
update_ema_every: 1
