T: 8
algo: dac
bc_weight: 0.01
d4rl: true
discount2: 1.0
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: half-t8-infer8-igin-sept13-nb-vecenv
n_inf_steps: 8
name: half-t8-infer8-igin-sept13-nb-vecenv
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
sampler_type: origin
tune_bc_weight: false
vec_env_eval: true
