T: 8
algo: dac
bc_weight: 0.01
d4rl: true
discount2: 1.0
env_name: hopper-medium-v2
format:
- stdout
- wandb
- csv
id: hopp-t8-infer2-ddpm-sept13-nb-vecenv
n_inf_steps: 2
name: hopp-t8-infer2-ddpm-sept13-nb-vecenv
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
sampler_type: ddpm
tune_bc_weight: false
vec_env_eval: true
