T: 8
algo: td3
bc_decay: 0.995
bc_lower_bound: 0.01
bc_upper_bound: 100.0
bc_weight: 1.0
coef: 1.0
consistency: false
debug: true
discount2: 0.999
env_name: halfcheetah-medium-v2
id: halfch-td3-bcw-low0.5-t8
name: halfch-td3-bcw-low0.5-t8
predict_epsilon: false
seed: 0
tune_bc_weight: false
value_threshold: 0.00028
