T: 4
ablation: true
algo: dql
bc_weight: 1.0
critic_ema: 1
d4rl: true
discount2: 1.0
env_name: hopper-medium-v2
format:
- stdout
- wandb
- csv
id: hopp-abla1-t4-infer2-ddpm-resample-sept20-nb-resample
n_inf_steps: 2
name: hopp-abla1-t4-infer2-ddpm-resample-sept20-nb-resample
num_steps_per_epoch: 5000
online: false
policy_delay: 1
predict_epsilon: false
resample: true
sampler_type: ddpm
test_critic: true
tune_bc_weight: false
update_ema_every: 5
vec_env_eval: true
