T: 4
algo: dac
bc_weight: 0.0
d4rl: false
discount2: 1.0
env_name: Demo-v0
format:
- stdout
- wandb
- csv
id: dac-t4-sept3-online-bc
name: dac-t4-sept3-online-bc
need_animation: true
num_steps_per_epoch: 50
online: true
predict_epsilon: false
vis_q: true
