T: 4
ablation: true
algo: dac
bc_weight: 1.0
d4rl: true
env_name: halfcheetah-medium-v2
format:
- stdout
- csv
id: dac-t4-bc1.0-sept6-dac-debug
name: dac-t4-bc1.0-sept6-dac-debug
num_epochs: 10000
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
test_critic: true
