T: 4
algo: ql
bc_weight: 1.0
coef: 1.0
consistency: false
discount2: 1.0
env_name: walker2d-medium-expert-v2
format:
- stdout
- wandb
- csv
id: walker-t4-sept13-main-medium-expert
name: walker-t4-sept13-main-medium-expert
predict_epsilon: false
seed: 0
tune_bc_weight: false
