T: 2
algo: ddd
bc_weight: 2.5
coef: 1.0
discount2: 0.999
early_stop: false
env_name: halfcheetah-medium-v2
iql_style: discount
lr_decay: false
seed: 0
num_steps_per_epoch: 1
format: ["stdout"]
predict_epsilon: false
