T: 2
algo: ql
bc_decay: 0.995
bc_lower_bound: 0.01
bc_upper_bound: 100.0
bc_weight: 0.1
coef: 1.0
consistency: false
discount2: 0.999
env_name: hopper-medium-v2
id: hopper-ql-bcw-low0.1-t2
name: hopper-ql-bcw-low0.1-t2
predict_epsilon: false
seed: 0
tune_bc_weight: false
value_threshold: 0.00028
