T: 4
algo: ql
bc_weight: 1.0
coef: 1.0
consistency: false
debug: true
discount2: 1.0
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: half-debug1-sept13-main-bc
name: half-debug1-sept13-main-bc
predict_epsilon: false
seed: 0
tune_bc_weight: false
