T: 8
algo: ql
bc_weight: 1.0
coef: 1.0
consistency: false
debug: false
discount2: 1.0
env_name: hopper-medium-v2
format:
- stdout
- wandb
- csv
id: hopper-t8-debug0-sept13-main-bc
name: hopper-t8-debug0-sept13-main-bc
predict_epsilon: false
seed: 0
tune_bc_weight: false
