T: 8
ablation: false
algo: dql
bc_weight: 1.0
coef: 1.0
consistency: false
discount2: 1.0
env_name: hopper-medium-v2
id: hopper-t8-flag0-sept12-nb-env
name: hopper-t8-flag0-sept12-nb-env
predict_epsilon: false
seed: 0
test_critic: false
tune_bc_weight: false
