algo: "dac" 
T: 1 
g_mdp: False 
norm_q: False 
consistency_coef: 0.0 
add_noise: True 
update_ema_every: 1 
name: "dac2td3-bc" 
id: "dac2td3-bc" 
# bc_weight: 1.0
predict_epsilon: False 
format: ['stdout', "wandb"]