T: 1
algo: ql
bc_decay: 0.995
bc_lower_bound: 0.01
bc_upper_bound: 100.0
bc_weight: 10.0
coef: 1.0
discount2: 0.999
env_name: walker2d-medium-v2
id: walker-ql-bc-control
name: walker-ql-bc-control
seed: 0
tune_bc_weight: true
value_threshold: 0.00028
