T: 8
algo: mac
d4rl: true
discount2: 1.0
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: half-t8-infer8-igin-roll1-sept19-nb-mac
len_rollout: 1
n_inf_steps: 8
name: half-t8-infer8-igin-roll1-sept19-nb-mac
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
sampler_type: origin
tune_bc_weight: false
vec_env_eval: true
