T: 512
algo: dac
bc_weight: 1.0
d4rl: false
env_name: Demo-v0
format:
  - stdout
  - wandb
  - csv
id: dac-demo-offline-t512
name: dac-demo-offline-t512
need_animation: true
num_steps_per_epoch: 1
online: false
predict_epsilon: false
update_ema_every: 1
vis_q: true
with_eval: false
