T: 8
algo: dql
bc_weight: 1.0
d4rl: true
discount2: 1.0
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: dql-envhalf-t8-resample1
name: dql-envhalf-t8-resample1
need_animation: true
need_entropy_test: true
num_epochs: 10000
num_steps_per_epoch: 10000
online: false
predict_epsilon: false
resample: true
update_ema_every: 1
