T: 8
algo: dql
bc_weight: 1.0
d4rl: true
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: dql-t8-oldparam
name: dql-t8-oldparam
num_epochs: 10000
num_steps_per_epoch: 100
online: false
predict_epsilon: false
