T: 4
algo: dql
d4rl: true
discount2: 0.999
env_name: walker2d-medium-v2
format:
- stdout
- wandb
- csv
id: dql-walker-norm_q-online-t4
name: dql-walker-norm_q-online-t4
need_animation: true
need_entropy_test: true
predict_epsilon: false
update_ema_every: 1
