T: 16
ablation: true
algo: dac
bc_weight: 0.01
d4rl: true
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: dac-t16-bc0.01-sept6-dac-bcw
name: dac-t16-bc0.01-sept6-dac-bcw
num_epochs: 10000
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
test_critic: true
