T: 1
algo: bc
bc_decay: 0.995
bc_lower_bound: 0.01
bc_upper_bound: 100.0
bc_weight: 1
coef: 1.0
discount2: 0.999
env_name: halfcheetah-medium-v2
id: halfch-bc
iql_style: discount
name: halfch-bc
seed: 0
std_threshold: 0.0001
tune_bc_weight: true
value_threshold: 0.00025
