T: 16
ablation: true
algo: dac
bc_weight: 0.0
d4rl: true
discount2: 1.0
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: half-t16-sept10-nb-online
name: half-t16-sept10-nb-online
num_epochs: 50000
num_steps_per_epoch: 500
online: false
predict_epsilon: false
seed: 0
test_critic: true
tune_bc_weight: false
