T: 1
ablation: true
algo: dac
bc_weight: 0.0
d4rl: true
discount2: 1.0
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: half-t1-sept10-nb-online
name: half-t1-sept10-nb-online
num_epochs: 5000
num_steps_per_epoch: 100
online: true
predict_epsilon: false
seed: 0
test_critic: true
tune_bc_weight: false
