T: 8
algo: dac
bc_weight: 0.01
d4rl: true
discount2: 1.0
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: half-t8-sept10-nb-t
name: half-t8-sept10-nb-t
num_steps_per_epoch: 5000
online: false
predict_epsilon: false
seed: 0
tune_bc_weight: false
