T: 8
algo: dac
bc_weight: 0.01
coef: 1.0
d4rl: true
discount2: 0.999
env_name: halfcheetah-medium-v2
format:
- stdout
- wandb
- csv
id: halfch-t8-sept10-dac-pre-tensor
name: halfch-t8-sept10-dac-pre-tensor
num_steps_per_epoch: 5000
online: false
pre_dataset: false
predict_epsilon: false
seed: 0
tune_bc_weight: false
