T: 1
algo: dac
bc_decay: 0.995
bc_lower_bound: 0.01
bc_weight: 5.0
coef: 1.0
discount2: 0.999
env_name: halfcheetah-medium-v2
id: halfch-bcw5.0
iql_style: discount
name: halfch-bcw5.0
seed: 0
std_threshold: 0.0001
tune_bc_weight: true
