T: 1
algo: dac
bc_decay: 0.995
bc_lower_bound: 0.001
bc_weight: 1.0
coef: 1.0
discount2: 0.999
env_name: halfcheetah-medium-v2
id: halfch-tune0-bcw1.0
iql_style: discount
named: halfch-tune0-bcw1.0
seed: 0
std_threshold: 0.0001
tune_bc_weight: false
