T: 1
algo: dac
bc_decay: 0.99
bc_lower_bound: 0.001
bc_weight: 2.5
coef: 1.0
discount2: 0.999
env_name: halfcheetah-medium-v2
id: halfch-time1
iql_style: discount
name: halfch-time1
seed: 0
std_threshold: 0.0001
tune_bc_weight: true
value_threshold: 0.00028
